[theme]
# A cor primária da Brocks
primaryColor = "#F25C38"

# O background geral do dashboard
backgroundColor = "#FFFFFF"

# O background do sidebar e cards
secondaryBackgroundColor = "#F4F6F8"

# Cor do Texto
textColor = "#0A0A0A"

# A fonte moderna
font = "sans serif"
